#pragma once

enum class GAME_EVENT
{
    EVENT_DEBUG_GENERATE_NEW_FIGURES,
    EVENT_MOVE_FIGURE_LEFT,
    EVENT_MOVE_FIGURE_RIGHT,
    EVENT_ROTATE_FIGURE,
    EVENT_ACCELERATE_FIGURE,
    DEFAULT
};